-- ============================================================
-- BOOKS / WORKS
-- ============================================================

create table if not exists public.books (

    book_id bigint primary key,

    work_key text unique not null,

    title text not null,

    author text,

    title_normalized text,

    author_normalized text,

    genre_list text,

    description text,

    pages_clean double precision,

    rating_clean double precision,

    totalratings bigint,

    length_category text
);


-- ============================================================
-- EDITIONS
-- ============================================================

create table if not exists public.editions (

    edition_id bigint primary key,

    book_id bigint not null
        references public.books(book_id)
        on delete cascade,

    work_key text not null,

    title text,

    author text,

    bookformat text,

    isbn text,

    isbn13 text,

    pages bigint,

    rating double precision,

    totalratings bigint,

    img text,

    link text
);


-- ============================================================
-- READING HISTORY
-- ============================================================

create table if not exists public.reading_history (

    id bigint generated by default as identity
        primary key,

    user_id uuid not null
        references auth.users(id)
        on delete cascade,

    book_id bigint not null
        references public.books(book_id)
        on delete cascade,

    status text not null,

    created_at timestamp with time zone
        default now(),

    unique(
        user_id,
        book_id
    )
);


-- ============================================================
-- BOOK RATINGS
-- ============================================================

create table if not exists public.book_ratings (

    id bigint generated by default as identity
        primary key,

    user_id uuid not null
        references auth.users(id)
        on delete cascade,

    book_id bigint not null
        references public.books(book_id)
        on delete cascade,

    rating integer not null
        check (
            rating >= 1
            and rating <= 5
        ),

    created_at timestamp with time zone
        default now(),

    unique(
        user_id,
        book_id
    )
);


-- ============================================================
-- RECOMMENDATION FEEDBACK
-- ============================================================

create table if not exists public.recommendation_feedback (

    id bigint generated by default as identity
        primary key,

    user_id uuid not null
        references auth.users(id)
        on delete cascade,

    source_book_id bigint not null
        references public.books(book_id)
        on delete cascade,

    recommended_book_id bigint not null
        references public.books(book_id)
        on delete cascade,

    rating integer
        check (
            rating >= 1
            and rating <= 5
        ),

    helpful boolean,

    created_at timestamp with time zone
        default now()
);


-- ============================================================
-- INDEXES
-- ============================================================

create index if not exists
idx_editions_book_id
on public.editions(book_id);


create index if not exists
idx_editions_title
on public.editions(title);


create index if not exists
idx_editions_author
on public.editions(author);


create index if not exists
idx_reading_history_user
on public.reading_history(user_id);


create index if not exists
idx_book_ratings_user
on public.book_ratings(user_id);


create index if not exists
idx_feedback_user
on public.recommendation_feedback(user_id);
-- ============================================================
-- ROW LEVEL SECURITY
-- ============================================================

alter table public.books
enable row level security;


alter table public.editions
enable row level security;


alter table public.reading_history
enable row level security;


alter table public.book_ratings
enable row level security;


alter table public.recommendation_feedback
enable row level security;


-- ============================================================
-- BOOKS
-- ============================================================

create policy "Anyone can read books"
on public.books
for select
to anon, authenticated
using (true);


-- ============================================================
-- EDITIONS
-- ============================================================

create policy "Anyone can read editions"
on public.editions
for select
to anon, authenticated
using (true);


-- ============================================================
-- READING HISTORY
-- ============================================================

create policy "Users can view their reading history"
on public.reading_history
for select
to authenticated
using (
    auth.uid() = user_id
);


create policy "Users can insert their reading history"
on public.reading_history
for insert
to authenticated
with check (
    auth.uid() = user_id
);


create policy "Users can update their reading history"
on public.reading_history
for update
to authenticated
using (
    auth.uid() = user_id
)
with check (
    auth.uid() = user_id
);


-- ============================================================
-- RATINGS
-- ============================================================

create policy "Users can view their ratings"
on public.book_ratings
for select
to authenticated
using (
    auth.uid() = user_id
);


create policy "Users can insert their ratings"
on public.book_ratings
for insert
to authenticated
with check (
    auth.uid() = user_id
);


create policy "Users can update their ratings"
on public.book_ratings
for update
to authenticated
using (
    auth.uid() = user_id
)
with check (
    auth.uid() = user_id
);


-- ============================================================
-- RECOMMENDATION FEEDBACK
-- ============================================================

create policy "Users can view their feedback"
on public.recommendation_feedback
for select
to authenticated
using (
    auth.uid() = user_id
);


create policy "Users can insert their feedback"
on public.recommendation_feedback
for insert
to authenticated
with check (
    auth.uid() = user_id
);
