-- ============================================================
-- BOOKS / WORKS
-- ============================================================

create table if not exists public.books (

    book_id bigint primary key,

    work_key text unique not null,

    title text not null,

    author text,

    title_normalized text,

    author_normalized text,

    genre_list text,

    description text,

    pages_clean double precision,

    rating_clean double precision,

    totalratings bigint,

    length_category text
);


-- ============================================================
-- EDITIONS
-- ============================================================

create table if not exists public.editions (

    edition_id bigint primary key,

    book_id bigint not null
        references public.books(book_id)
        on delete cascade,

    work_key text not null,

    title text,

    author text,

    bookformat text,

    isbn text,

    isbn13 text,

    pages bigint,

    rating double precision,

    totalratings bigint,

    img text,

    link text
);


-- ============================================================
-- READING HISTORY
-- ============================================================

create table if not exists public.reading_history (

    id bigint generated by default as identity
        primary key,

    user_id uuid not null
        references auth.users(id)
        on delete cascade,

    book_id bigint not null
        references public.books(book_id)
        on delete cascade,

    status text not null,

    created_at timestamp with time zone
        default now(),

    unique(
        user_id,
        book_id
    )
);


-- ============================================================
-- BOOK RATINGS
-- ============================================================

create table if not exists public.book_ratings (

    id bigint generated by default as identity
        primary key,

    user_id uuid not null
        references auth.users(id)
        on delete cascade,

    book_id bigint not null
        references public.books(book_id)
        on delete cascade,

    rating integer not null
        check (
            rating >= 1
            and rating <= 5
        ),

    created_at timestamp with time zone
        default now(),

    unique(
        user_id,
        book_id
    )
);


-- ============================================================
-- RECOMMENDATION FEEDBACK
-- ============================================================

create table if not exists public.recommendation_feedback (

    id bigint generated by default as identity
        primary key,

    user_id uuid not null
        references auth.users(id)
        on delete cascade,

    source_book_id bigint not null
        references public.books(book_id)
        on delete cascade,

    recommended_book_id bigint not null
        references public.books(book_id)
        on delete cascade,

    rating integer
        check (
            rating >= 1
            and rating <= 5
        ),

    helpful boolean,

    created_at timestamp with time zone
        default now()
);


-- ============================================================
-- INDEXES
-- ============================================================

create index if not exists
idx_editions_book_id
on public.editions(book_id);


create index if not exists
idx_editions_title
on public.editions(title);


create index if not exists
idx_editions_author
on public.editions(author);


create index if not exists
idx_reading_history_user
on public.reading_history(user_id);


create index if not exists
idx_book_ratings_user
on public.book_ratings(user_id);


create index if not exists
idx_feedback_user
on public.recommendation_feedback(user_id);
